# Generated by Django 4.2.7 on 2023-12-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='result',
        ),
        migrations.AddField(
            model_name='gameround',
            name='choice',
            field=models.CharField(choices=[('rock', 'rock'), ('paper', 'paper'), ('scissors', 'scissors')], default='rock', max_length=255),
        ),
        migrations.AddField(
            model_name='gameround',
            name='whichRound',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three')], default='one', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.competition')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameround',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.competition'),
        ),
    ]
