# Generated by Django 4.2.7 on 2023-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_competition_remove_gameround_opponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='whichRound',
            field=models.CharField(choices=[('two', 'two'), ('one', 'one'), ('three', 'three')], default='one', max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
