# Generated by Django 4.2.7 on 2023-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameround_whichround_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='whichRound',
            field=models.CharField(choices=[('three', 'three'), ('one', 'one'), ('two', 'two')], default='one', max_length=255),
        ),
    ]
